### ISSUE TITLE
Introduce shorthands for operations?

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/jsbi#1]
If there’s demand for it, we could consider introducing shorthands for operations (e.g. `exp` for `exponentiate`, and so on). The current method names follow the spec proposal.

If you have suggestions for naming schemes, please speak up here!

**Comment by mathiasbynens** [comment]
I personally don’t think there’s much value in adding shorthands for operations at this point. It’s okay for there to be only one true way of doing things. We can always revisit this later; OTOH, if we add shorthands now, we may not be able to get rid of them.

**Comment by jakobkummerow** [comment]
In the interest of easy transpilation, I don't think we'll do this.
