### ISSUE TITLE
 How to convert an array back to JSBI

### ISSUE THREAD

**Issue by clarkchen** [GoogleChromeLabs/jsbi#104]
```
let x = JSBI.BigInt(Math.pow(10,10))

console.log(x) 
// JSBI(2) [ 336323584, 9, sign: false ]
```

how to convert ` JSBI(2) [ 336323584, 9, sign: false ]` back to JSBI object

thx~

**Comment by Yaffle** [comment]
x is the JSBI object, console.log prints it as array as it is confused by the fact that it is a subclass of an array

**Comment by jakobkummerow** [comment]
It's literally [at the top of the README](https://github.com/GoogleChromeLabs/jsbi#usage):

> ```
> console.log(String(max));
> ```
> Note: explicitly call `toString` on any `JSBI` instances when `console.log()`ing them to see their numeric representation (e.g. `String(max)` or `max.toString()`). Without it (e.g. `console.log(max)`), you’ll instead see the object that represents the value.
