### ISSUE TITLE
 uniswap.org/ext 

### ISSUE THREAD

**Issue by Maungmaunglwin096062286** [GoogleChromeLabs/jsbi#105]

**Comment by Maungmaunglwin096062286** [comment]
- [ ] ![Screenshot_၂၀၂၄၁၂၀၇_၀၁၂၃၀၁_Trust Wallet.jpg](https://github.com/user-attachments/assets/41944831-c3f9-4537-93f9-5e14d8d957eb)

**Comment by jakobkummerow** [comment]
No description provided.
