### ISSUE TITLE
Implement BigInt.asIntN and BigInt.asUintN

### ISSUE THREAD

**Issue by pmurias** [GoogleChromeLabs/jsbi#11]
Implementing those two static methods would help with porting code that uses them.

**Comment by y3llowcake** [comment]
I was excited to find this package and then disappointed to find it doesn't implement these functions.

**Comment by pmurias** [comment]
> I was excited to find this package and then disappointed to find it doesn't implement these functions.

https://github.com/perl6/nqp/blob/master/src/vm/js/nqp-runtime/as-int-n.js - I use a super naive and inefficient direct implementation of the spec for those. I guess I should do a proper implementation as a PR to jsbi at some point.

**Comment by Yaffle** [comment]
Personally, I don't need it, but:
```javascript
JSBI.BigInt.asUintN = function (bits, bigint) {
  const p2bits = JSBI.leftShift(JSBI.BigInt(1), JSBI.BigInt(bits));
  const mod = JSBI.bitwiseAnd(JSBI.BigInt(bigint), JSBI.subtract(p2bits, JSBI.BigInt(1)));
  return mod;
};
JSBI.BigInt.asIntN = function (bits, bigint) {
  const p2bits = JSBI.leftShift(JSBI.BigInt(1), JSBI.BigInt(bits));
  const mod = JSBI.bitwiseAnd(JSBI.BigInt(bigint), JSBI.subtract(p2bits, JSBI.BigInt(1)));
  return JSBI.greaterThanOrEqual(mod, JSBI.subtract(p2bits, mod)) ? JSBI.subtract(mod, p2bits) : mod;
};
```
It is almost the same as @pmurias suggested.
