### ISSUE TITLE
The remainder method returns wrong result for some values

### ISSUE THREAD

**Issue by pmurias** [GoogleChromeLabs/jsbi#13]
const jsbi = require('jsbi');

const a = '2788589391528142331873770897124985830679715361908029740727468171087321981075';
const b = '170141183460469231731687303715884105727';

console.log('wrong:', jsbi.remainder(jsbi.BigInt(a), jsbi.BigInt(b)).toString());
console.log('correct', BigInt(a) % BigInt(b));

**Comment by Yaffle** [comment]
https://github.com/GoogleChromeLabs/jsbi/blob/master/jsbi.mjs#L1460 this line looks strange...

**Comment by pmurias** [comment]
Would be great to have that released as I need that fix to use jsbi.

**Comment by jakobkummerow** [comment]
It's just been released as https://www.npmjs.com/package/jsbi/v/2.0.3.
