### ISSUE TITLE
[discussion] migration

### ISSUE THREAD

**Issue by FranklinYu** [GoogleChromeLabs/jsbi#21]
The idea of migration is mentioned in README and I'm interested. I did some quick search. Candidates:
  - [Lebab](https://www.npmjs.com/package/lebab): JavaScript modernizer (reversed Babel)
  - [codemod](https://github.com/codemod-js/codemod): Babel plugin
  - [jscodeshift](https://github.com/facebook/jscodeshift)

Actually I would prefer an Editor plugin, since it will typically only be used once in a project.

**Comment by mathiasbynens** [comment]
What did you have in mind exactly? Is there anything left to do now that we have https://github.com/GoogleChromeLabs/babel-plugin-transform-jsbi-to-bigint?

**Comment by FranklinYu** [comment]
> it behaves exactly like native BigInts will when they become available, so to migrate to those, you can mechanically update your code’s syntax; no re-thinking of its logic will be required. (There is no tool for this migration yet, but it should be easy to build one. Help welcome.)

from README

**Comment by jakobkummerow** [comment]
Sorry, that bit of the README was outdated. It's fixed now. See @mathiasbynens' comment (or the updated README) for the existing tool. Thanks for your willingness to help though :-)
