### ISSUE TITLE
Serialization to Uint8Array.

### ISSUE THREAD

**Issue by iwasaki-kenta** [GoogleChromeLabs/jsbi#23]
Are there any functions available in the library to write a BigInt to a DataView? Or perhaps retrieve a Uint8Array from a BigInt instance?

Looking to polyfill for: `DataView.getBigUint64(byteOffset, littleEndian)`.

**Comment by jakobkummerow** [comment]
> Are there any functions available in the library to write a BigInt to a DataView?

Not yet; see issue #4 . I think this request is essentially a dupe of that issue.

> Or perhaps retrieve a Uint8Array from a BigInt instance?

No, JSBI shouldn't provide any functionality that native BigInts don't have.
