### ISSUE TITLE
transpile the UMD to ES5

### ISSUE THREAD

**Issue by janhommes** [GoogleChromeLabs/jsbi#24]
We have an issue with a library that imports JSBI and should be used in a browser. Especially it fails in IE11 because of >ES5 syntax used here:
https://unpkg.com/jsbi@2.0.5/dist/jsbi-umd.js

Just wanted to know if there is any reason why the UMD module is not traspiled to ES5? That would make the usage of libraries much easier, especially as the Rollup documentation says that all external dependencies should be [transpiled already when you using it with babel](https://rollupjs.org/guide/en/#babel).

The lib and the PR is: https://github.com/vasturiano/ip.js/pull/1

Thanks
Jan

**Comment by mathiasbynens** [comment]
For each generated bundle, we have to transpile to _some_ target. When determining the target, the question is which environments you need to support. What should the lowest common denominator be? Is it Node.js v10? IE11? IE6? The answer to this question is different for every project.

For our UMD build, the target is currently ES2015. If you need to support older environments such as IE11, we figured you can hook jsbi up to your custom transpilation pipeline and create a bundle that works for your use case. However, I see in https://github.com/vasturiano/ip.js/pull/1#issuecomment-509075749 that this is not an option for this particular project.

Per your request, we're open to a PR that changes the UMD output to ES5.

**Comment by janhommes** [comment]
Fixed here #26
