### ISSUE TITLE
JSON.stringify() doesn't know how to serialize a BigInt

### ISSUE THREAD

**Issue by cliffhall** [GoogleChromeLabs/jsbi#30]
Not certain how to handle this situation:

```
    TypeError: Do not know how to serialize a BigInt
        at JSON.stringify (<anonymous>)

      39 |     toObject() {
    > 40 |         return JSON.parse(JSON.stringify(this));
         |                                ^
      41 |     }
```

**Comment by jakobkummerow** [comment]
Working as intended/spec'ed: https://tc39.es/proposal-bigint/#sec-serializejsonproperty (step 10).

In short, the background is that JSON is so commonly used among all sorts of different systems and programming languages that it is effectively impossible to add anything to the format without breaking compatibility in some crucial case.

You can define your own `.toJSON()` function, and pass a corresponding "reviver" function as an argument to `JSON.parse()`. That way, at least you have control over any (backwards) compatibility issues.

**Comment by cliffhall** [comment]
@jakobkummerow Ok, makes sense. For anyone else stumbling upon this, the verified TL;DR fix for the above problem is:

```
    toObject() {
        return JSON.parse(JSON.stringify(this), (key, value) =>
            typeof value === 'bigint'
                ? value.toString()
                : value // return everything else unchanged
        );
    }
```

**Comment by phoenixbeats01** [comment]
@ADTC answer will only work with pure javascript. With typescript I get the error: `TS2339: Property 'toJSON' does not exist on type 'BigInt'.`

**Comment by mohamed040406** [comment]
> @ ADTC answer will only work with pure javascript. With typescript I get the error: `TS2339: Property 'toJSON' does not exist on type 'BigInt'.`

you can do this if you are using typescript
```ts
(BigInt.prototype as any).toJSON = function () {
  return this.toString();
};
```

**Comment by HolgerJeromin** [comment]
Or cleaner with the "I know what I do" feature:

````ts
BigInt.prototype["toJSON"] = function () {
  return this.toString();
};

**Comment by brunoamancio** [comment]
> 

Element implicitly has an 'any' type because expression of type '"toJSON"' can't be used to index type 'BigInt'.
  Property 'toJSON' does not exist on type 'BigInt'.ts(7053)

**Comment by brunoamancio** [comment]
> Or cleaner with the "I know what I do" feature:
> 
> ```ts
> BigInt.prototype["toJSON"] = function () {
>   return this.toString();
> };
> ```

Element implicitly has an 'any' type because expression of type '"toJSON"' can't be used to index type 'BigInt'.
  Property 'toJSON' does not exist on type 'BigInt'.ts(7053)

**Comment by HolgerJeromin** [comment]
> Element implicitly has an 'any' type because expression of type '"toJSON"' can't be used to index type 'BigInt'.
Property 'toJSON' does not exist on type 'BigInt'.ts(7053)

Oh, I had [`suppressImplicitAnyIndexErrors: true`](https://www.typescriptlang.org/tsconfig#suppressImplicitAnyIndexErrors) in my config. Edited my example. Thanks!

**Comment by noskill24** [comment]
Polyfill:

    // Polyfill: BigInt.prototype.toJSON 

    (function(global, undefined) {
      "use strict";
      if (global.BigInt.prototype.toJSON === undefined) {
        global.Object.defineProperty(global.BigInt.prototype, "toJSON", {
            value: function() { return this.toString(); },
            configurable: true,
            enumerable: false,
            writable: true
        });
      }
    })(window !== void 0 ? window : typeof global !== void 0 ? global : typeof self !== void 0 ? self : this);

**Comment by noskill24** [comment]
Polyfill:

    // Polyfill: BigInt.prototype.toJSON 

    (function(global, undefined) {
      if (global.BigInt.prototype.toJSON === undefined) {
        global.Object.defineProperty(global.BigInt.prototype, "toJSON", {
            value: function() { return this.toString(); },
            configurable: true,
            enumerable: false,
            writable: true
        });
      }
    })(window !== void 0 ? window : typeof global !== void 0 ? global : typeof self !== void 0 ? self : this);

**Comment by lucasvalentee** [comment]
If you're trying to use this with Typescript, I suggest you create a .ts or .js file with:

```typescript
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unreachable code error
BigInt.prototype.toJSON = function (): number {
  return this.toString();
};
```

After that, you must import or require this file in your main file (like index.ts/.js or main.ts, etc).

If you are trying to run tests with Jest, you must add this file in the installation configuration. These settings can be created in package.json with "jest: { .... }" or in a file called jest.config.ts (create this in the root).

Example:

```typescript
export default {
   testTimeout: 30000,
  moduleFileExtensions: ['js', 'json', 'ts'],
  **setupFiles: ['./my_config_file'],**
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
}
```

At this point you can create a test module, with many configs, and create an index file that imports all the configs, and just pass this index file in the setupFiles config from jest.

**Comment by sullof** [comment]
The issue with serializing a BigInt as a string is that during the parsing you must know what any property is to know which one should stay as strings and which one should become big integers.

It would be better to use an approach similar to how BigNumber instances are stringified like this
```json
{ 
  "type": "BigNumber", 
  "hex": "0x01e848"
}
```

I just added to [bigNumberify](https://github.com/sullof/bignumberify) support for BigInt values, so that the BigInt `125000n` will be encoded as
```json
{ 
  "type": "BigInt", 
  "hex": "0x01e848"
}
```
and parsed back without ambiguities. Any feedback would be appreciated.

**Comment by Zetazzz** [comment]
I guess the process can be like this:
  stringify:
```
function replacer(key, value) {
  if (typeof value === 'bigint') {
    return {
      type: 'bigint',
      value: value.toString()
    };
  } else {
    return value;
  }
}

const obj = {
  smallInt: 1,
  n: BigInt(9007199254740991),
};

let s = JSON.stringify(obj, replacer) //{"smallInt":1,"n":{"type":"bigint","value":"9007199254740991"}}
```

parse:
```
function reviver(key, value) {
  if (value && value.type == 'bigint') {
    return BigInt(value.value);  
  }
  return value;
}

const parsedObj = JSON.parse(s, reviver); //{ smallInt: 1, n: 9007199254740991n }
```

Hope this makes sense

**Comment by kodejuice** [comment]
> I guess the process can be like this: stringify:
> 
> ```
> function replacer(key, value) {
>   if (typeof value === 'bigint') {
>     return {
>       type: 'bigint',
>       value: value.toString()
>     };
>   } else {
>     return value;
>   }
> }
> 
> const obj = {
>   smallInt: 1,
>   n: BigInt(9007199254740991),
> };
> 
> let s = JSON.stringify(obj, replacer) //{"smallInt":1,"n":{"type":"bigint","value":"9007199254740991"}}
> ```
> 
> parse:
> 
> ```
> function reviver(key, value) {
>   if (value && value.type == 'bigint') {
>     return BigInt(value.value);  
>   }
>   return value;
> }
> 
> const parsedObj = JSON.parse(s, reviver); //{ smallInt: 1, n: 9007199254740991n }
> ```
> 
> Hope this makes sense

This is it!
Here i added a wrapper function:

```javascript
// Wrapper around JSON stringify/parse methods to support bigint serialization

function replacer(key, value) {
  if (typeof value === "bigint") {
    return {
      __type: "bigint",
      __value: value.toString(),
    };
  } else {
    return value;
  }
}

function reviver(key, value) {
  if (value && value.__type == "bigint") {
    return BigInt(value.__value);
  }
  return value;
}

export const json_stringify = (obj) => {
  return JSON.stringify(obj, replacer);
};

export const json_parse = (s) => {
  return JSON.parse(s, reviver);
};
```

**Comment by SalamandraDevs** [comment]
> If you're trying to use this with Typescript, I suggest you create a .ts or .js file with:
> 
> ```ts
> // eslint-disable-next-line @typescript-eslint/ban-ts-comment
> // @ts-ignore: Unreachable code error
> BigInt.prototype.toJSON = function (): number {
>   return this.toString();
> };
> ```

I found this solution more elegant, works for typescript too:

```ts
Object.defineProperty(BigInt.prototype, "toJSON", {
        get() {
            "use strict";
            return () => String(this);
        }
    });
```
 
 As many of you have commented before, you can put this into a file and import it to have it into the gobal scope.

**Comment by SashaDesigN** [comment]
> Wouldn't it be easier to just _monkey patch (hijack)_ `BigInt`? That's [the MDN recommendation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json).
> 
> ```js
> BigInt.prototype.toJSON = function() { return this.toString() }
> ```
> 
> If you do it this way, you don't have to add an anonymous function into every call of `JSON.stringify`. It applies globally to all such calls.

worked for me elegant

**Comment by orhan-cmd** [comment]
`JSON.parse(JSON.stringify(String(this)))` worked for me.

**Comment by joematune** [comment]
Modifying the global BigInt and involving `@ts-ignore` is a code smell. @Zetazzz provided [a solution](https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-1609631034) that highlights the built-in ability to solve this problem in both JavaScript and TypeScript.

Please don't modify the global so that the next developer has to spend time finding your elegant solution :pray:

```ts
function bigIntReplacer(_key: string, value: any): any {
  return typeof value === 'bigint' ? value.toString() : value;
}

JSON.stringify({ "my_big_int": 1122n }, bigIntReplacer);
// '{"my_big_int":"1122"}'
```

**Comment by remotemerge** [comment]
I am using strict typing, and the following setup works for me:

```typescript
// src/types/global.d.ts
interface BigInt {
  toJSON: () => string;
}
```

```typescript
// src/main.ts
BigInt.prototype.toJSON = function () {
  return this.toString();
};
```

**Comment by JohanAlteruna** [comment]
The JSON specification allows arbitrarily large integers, and in some cases you might want to actually serialize bigints as syntactical JSON integers and not strings; e.g. when communicating with services that properly support parsing such integers. You can now do this using [`JSON.rawJSON`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/rawJSON) (if your runtime supports it). 

For example: 
```javascript
function bigIntReplacer(key, value) {
  if (typeof value === "bigint") {
    return JSON.rawJSON(value.toString());
  } else {
    return value;
  }
}

// Returns '{"foo":119257819285912598125125}'
JSON.stringify({ foo: 119257819285912598125125n }, bigIntReplacer)
```

Note however that this only works for serialization and not for parsing.
