### ISSUE TITLE
typeof JSBI instance returns "object" not "bigint"

### ISSUE THREAD

**Issue by cliffhall** [GoogleChromeLabs/jsbi#38]
![Screen Shot 2020-01-20 at 4 01 50 PM](https://user-images.githubusercontent.com/871933/72757511-26cc0d80-3b9e-11ea-9893-cfa07001392a.png)

I took the documentation at face value when it said to use `typeof === 'bigint'` to recognize an instance. Now I'm remediating. :(

**Comment by cliffhall** [comment]
My bad should've been checking instanceof JSBI :(

**Comment by mathiasbynens** [comment]
This is documented here: https://github.com/GoogleChromeLabs/jsbi#how
