### ISSUE TITLE
Parser accepts empty string as zero

### ISSUE THREAD

**Issue by decafbad** [GoogleChromeLabs/jsbi#41]
```
> jsbi.BigInt('')
JSBI(0) [ sign: false ]
```

**Comment by jakobkummerow** [comment]
Yes, I believe that is the correct behavior.

Compare native BigInt behavior:
```js
> BigInt("")
0n
```

Spec: "The mathematical value of StringNumericLiteral:::[empty] is 0." (https://tc39.es/ecma262/#sec-runtime-semantics-mv-s, which is applicable for `BigInt(value)` if `value` is a string).
