### ISSUE TITLE
Incorrect bitwiseAnd result

### ISSUE THREAD

**Issue by zaidka** [GoogleChromeLabs/jsbi#44]
The following code demonstrates the issue and compares the result against native BigInt implementation:

    const a = "0b10000010001000100010001000100010001000100010001000100010001000100";
    const b = "0b10000000000000000000000000000000000000000000000000000000000000000";

    const jsbiRes = JSBI.bitwiseAnd(JSBI.BigInt(a), JSBI.bitwiseNot(JSBI.BigInt(b)));
    const nativeRes = BigInt(a) & ~BigInt(b);

    console.log("A:", a);
    console.log("B:", b);
    console.log("JSBI A & ~B:", jsbiRes.toString(2));
    console.log("Native A & ~B:", nativeRes.toString(2));

This is the output I get running in Node v12.16.3 using JSBI v3.1.2:

    A: 0b10000010001000100010001000100010001000100010001000100010001000100
    B: 0b10000000000000000000000000000000000000000000000000000000000000000
    JSBI A & ~B: 10000010001000100010001000100010001000100010001000100010001000100
    Native A & ~B: 10001000100010001000100010001000100010001000100010001000100

**Comment by jakobkummerow** [comment]
Good catch! Thanks to @zaidka for the report, and thanks to @Yaffle for the fix!

**Comment by jakobkummerow** [comment]
Fixed.
