### ISSUE TITLE
Possibly broken in IE11

### ISSUE THREAD

**Issue by Miladiir** [GoogleChromeLabs/jsbi#47]
I noticed that JSBI is broken in a test application when running in IE11.

When I exclude JSBI in webpacks babel-loader exclude (jsbi is parsed like the rest of my code):

![grafik](https://user-images.githubusercontent.com/1358063/92312878-6d536880-efc5-11ea-9d38-05b86c1a9367.png)
This possibly points to:
```javascript
if (!_(t) || i(t) !== t) throw new RangeError("The number " + t + " cannot be converted to BigInt because it is not an integer");
```
I use core-js@3 and regenerator-runtime as polyfills. Maybe I need something else as well?

When I do not exlude JSBI and treat it like any other dependency (jsbi is included in babel-loader):
![grafik](https://user-images.githubusercontent.com/1358063/92312924-f1a5eb80-efc5-11ea-9cf4-072a3f11656d.png)
This time it is unfortunately absolutely impossible to tell what upsets poor IE. Maybe its the same statement, who knows 🤷‍♂️.

Is the UMD version tested? Works fine in Firefox 80, but not in IE11.

I also noticed https://github.com/GoogleChromeLabs/jsbi/issues/42. I tested importing the common-js and mjs versions directly, however I still get similar results. IE is broken while Firefox works.

**Comment by glr0221** [comment]
@Miladiir 

I was about to use this library for a project of mine. Did this library ever work for IE11? I mean if there was a version of this  library that worked for IE11? Currently i need support for two core objects/functions BigInt() and getBigUint64(). Thank you.

**Comment by jakobkummerow** [comment]
Looks like IE11 doesn't support `Math.imul` and `Math.clz32`, which JSBI uses. At least, that's the result I get when I comment out "minify()" in rollup.config.js, regenerate the UMD version, and test `var a = JSBI.BigInt('12345678901234567890')` with that on an IE11 VM.

As a short-term workaround, you can provide a very simple polyfill (which does _not_ have the proper semantics, but is good enough for JSBI): 

```
if (!Math.imul) {
  Math.imul = function(a, b) {
    return ((a & 0xFFFF) * (b & 0xFFFF)) | 0;
  }
}
if (!Math.clz32) {
  Math.clz32 = function(x) {
    if (x === 0) return 32;
    return 31 - Math.floor(Math.log(x >>> 0) * Math.LOG2E);
  }
}
```

If you're worried about breaking other modules that might want to use these functions, you can find functionally fully correct polyfills on MDN.

I know next to nothing about Babel. Presumably it has a way to polyfill Math functions, but I don't know how to make it do that.

**Comment by Yaffle** [comment]
@jakobkummerow ,
```javascript
if (!Math.clz32) {
  Math.clz32 = function(x) {
    if (x === 0) return 32;
    return 31 - Math.floor(Math.log(**(x >>> 0) + 0.5**) * Math.LOG2E);
  }
}
```

**Comment by jakobkummerow** [comment]
@Yaffle : interesting fix, thanks! I actually copied that line from MDN; turns out different translations of the Math.clz32 page provide different polyfills, at least two of them omit the `+0.5` (which I can confirm is buggy e.g. for `x = 0x10000000`), a few others use `/ Math.LN2` instead of `* Math.LOG2E`, which also avoids the issue (yay for finite precision math!). Oh well, or one could implement bit fiddling.

I'll edit my earlier post to avoid any confusion.

**Comment by Miladiir** [comment]
Does that mean that the target only has transformed syntax, but does not include the proper polyfills? Thats really strange. Is that a misconfiguration or on purpose. Maybe a maintainer can clarify. I thank you for figuring out the problem.

**Comment by mathiasbynens** [comment]
> Looks like IE11 doesn't support `Math.imul` and `Math.clz32`, which JSBI uses. At least, that's the result I get when I comment out "minify()" in rollup.config.js, regenerate the UMD version, and test `var a = JSBI.BigInt('12345678901234567890')` with that on an IE11 VM.
> 
> As a short-term workaround, you can provide a very simple polyfill (which does _not_ have the proper semantics, but is good enough for JSBI):
> 
> ```js
> if (!Math.imul) {
>   Math.imul = function(a, b) {
>     return ((a & 0xFFFF) * (b & 0xFFFF)) | 0;
>   }
> }
> if (!Math.clz32) {
>   Math.clz32 = function(x) {
>     if (x === 0) return 32;
>     return 31 - (Math.log(x >>> 0) / Math.LN2 | 0) | 0;
>   }
> }
> ```
> 
> If you're worried about breaking other modules that might want to use these functions, you can find functionally fully correct polyfills on MDN.

IMHO this would be the best approach, except preferably we wouldn’t install on `Math`, but just keep these as local helper utilities that we don‘t expose globally or on any built-ins.

**Comment by glr0221** [comment]
I just wanted to say, I have successfully used JSBI with IE. Thank you so much @jakobkummerow @mathiasbynens @Miladiir
