### ISSUE TITLE
JSBI Instance's prototype lost when passed as a message via window.postMessage API

### ISSUE THREAD

**Issue by F3n67u** [GoogleChromeLabs/jsbi#50]
If post a JSBI.BigInt object via `window.postMessage` like this:

```
window.postMessage({ bi: JSBI.BigInt(1) });
```

In the other side, the received `bi` attribute will be a plain JavaScript Object instead of a JSBI.BigInt instance. `bi instanceof JSBI` will return false.

If I pass the received `bi` as a param of JSBI.add like this:

```
JSBI.add(bi, JSBI.BigInt(1))
```

The below error will throw:

```
TypeError: e.__clzmsd is not a function
```

Have a look into `window.postMessage` [API Doc](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage):

>  message
Data to be sent to the other window. The data is serialized using the structured clone algorithm. This means you can pass a broad variety of data objects safely to the destination window without having to serialize them yourself. [1]

[The structured clone algorithm ](https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal)will serialize JSBI Object to a plain JavaScript Object, so the prototype will certainly lost.

The structured clone algorithm support the new native [BigInt](https://v8.dev/features/bigint) type. But If I want use JSBI as a polyfill of the new native BigInt in a `window.postMessage` case, any solution to this problem?

**Comment by jakobkummerow** [comment]
I don't think it's possible to customize `postMessage` behavior, so I can't see a way to fix this on the JSBI library side.

That leaves you with local workarounds. You can manually convert the JSBI.BigInt object to a string on the sender side, and parse it back to a JSBI.BigInt on the receiver side.
The drawback is that this has a (small) efficiency cost. If/when you migrate to native BigInts, you can drop the workaround (but there's no immediate urgency to do so, as the technique is fully compatible).

Somewhat more hackily, you can also restore the prototype of the cloned object on the receiving side: `bi.__proto__ = JSBI.BigInt.prototype` should do the trick.
Benefit: faster (which is irrelevant if you can't even measure it)
Drawback: hackier
(This should still be compatible with migrating to native BigInts, where it'll simply turn into an unnecessary no-op, just like 
`let number = 42; number.__proto__ ="put anything you want here, nobody cares";`.)
