### ISSUE TITLE
Is there a way to do get a logarithm of a jsbi number?

### ISSUE THREAD

**Issue by sagivo** [GoogleChromeLabs/jsbi#54]
I need to get the log of a jsbi number. Is there a way to do it?

**Comment by jakobkummerow** [comment]
No, sorry. JSBI implements what ECMAScript defines for BigInts, and there's currently no `log` for them.

My understanding is that there were vague plans to do a follow-up proposal adding more functionality for BigInts; I don't know what has become of that idea.

See https://github.com/tc39/proposal-bigint/issues/205 for an earlier related request (bit length would be the rounded base-2 logarithm).
