### ISSUE TITLE
Math.floor function not working with Big integers

### ISSUE THREAD

**Issue by spherityshivam** [GoogleChromeLabs/jsbi#55]
Hi Team , I am using JSBI — pure-JavaScript BigInts   library , It is giving me issues when i am using Bitintegers with Math.floor function . 

Please help me with this 

Best Regards
Sethi Shivam

**Comment by jakobkummerow** [comment]
This is expected. `Math.floor` (like the other `Math.*` functions) doesn't work with real BigInts, so it doesn't work with JSBI BigInts either.

(For `floor` (and `ceil` and `round`) in particular, there's no reason to use them with BigInts anyway -- as the name implies, BigInts are integers, so they never have a fractional part, so if `Math.floor` or an equivalent function existed for them, it would always return the input unmodified. Like so: `function BigIntFloor(bigint) { return bigint; }`)
