### ISSUE TITLE
Cannot read property 'BigInt' of undefined

### ISSUE THREAD

**Issue by tqk2811** [GoogleChromeLabs/jsbi#56]
in App.ts
```
import JSBI from 'jsbi';
const TokenCount_Bignum = JSBI.BigInt(2);
```
did i missing something?
jsbi ver 3.1.5

**Comment by xyunsh** [comment]
same issue

**Comment by Yaffle** [comment]
Try native modules without any ts and bundlers

**Comment by tqk2811** [comment]
I found solution long time ago
```
import * as JSBI from 'jsbi/dist/jsbi-umd.js'
```

**Comment by xyunsh** [comment]
``` TypeScript
import * as JSBI from 'jsbi';
// @ts-ignore
const TokenCount_Bignum = JSBI.BigInt(2);

console.log(TokenCount_Bignum);
```

This will also work, but the ts check needs to be ignored

**Comment by xyunsh** [comment]
> ```ts
> import * as JSBI from 'jsbi';
> // @ts-ignore
> const TokenCount_Bignum = JSBI.BigInt(2);
> 
> console.log(TokenCount_Bignum);
> ```
> 
> This will also work, but the ts check needs to be ignored

Add a line to the end of jsbi.d.ts
```
export = JSBI;
```
can be passed by ts checking
