### ISSUE TITLE
(-(2n**64n - 1n)) >> 32n

### ISSUE THREAD

**Issue by Yaffle** [GoogleChromeLabs/jsbi#57]
JSBI.signedRightShift(JSBI.unaryMinus(JSBI.subtract(JSBI.exponentiate(JSBI.BigInt(2), JSBI.BigInt(64)), JSBI.BigInt(1))), JSBI.BigInt(32)).toString()
gives "0"
which is wrong, seems

**Comment by jakobkummerow** [comment]
Confirmed; JSBI is missing the equivalent of https://chromium-review.googlesource.com/c/v8/v8/+/2561618.

Fix: https://github.com/GoogleChromeLabs/jsbi/pull/58
