### ISSUE TITLE
URGENT 3.2.0 is very broken

### ISSUE THREAD

**Issue by thanpolas** [GoogleChromeLabs/jsbi#68]
I just upgraded to 3.2.0 and I get JSBI.BigInt is undefined error. Please verify the build.

**Comment by HolgerJeromin** [comment]
Probably related to #67
But I think the developers needs more information about your setup. (what prints the error message?)

**Comment by thanpolas** [comment]
Simple access to `JSBI.BigInt()` breaks. 

Step to reproduce:

```sh
npm install jsbi --save
```

### app.js

```js
console.log('JSBI.BigInt:', JSBI.BigInt);
```

**Comment by mathiasbynens** [comment]
Yes, this is likely due to #67. I’ll take a look. cc @12wrigja

**Comment by mathiasbynens** [comment]
Workaround:

```
const JSBI = require('jsbi').default;
```

But yeah we should try to restore the old behavior of exporting JSBI directly (and not as a named export called `default`) in the CommonJS bundle.

**Comment by thanpolas** [comment]
thank you Mathias ❤️

**Comment by gitmalong** [comment]
Using v3.2.1 in a Typescript project

1) Imported with `const JSBI = require('jsbi').default;`

```
   TypeError: Cannot read property 'subtract' of undefined

    > 38 |         const amount = JSBI.subtract(
```

**Comment by 12wrigja** [comment]
With v3.2.1 I believe Mathias fixed this so the above workaround is no longer necessary, and you should instead be able to write

```
const JSBI = require('JSBI');

JSBI.substract(...);
```
