### ISSUE TITLE
UMD bundle of v3.2.5 will throw TypeError: h.__initializeDigits is not a function

### ISSUE THREAD

**Issue by Leslie-Wong-H** [GoogleChromeLabs/jsbi#79]
Usage: 

![image](https://user-images.githubusercontent.com/27696701/137914131-063476f2-e47e-4127-825a-27d93c65a856.png)

The Webpack build bundle will throw TypeError:

![image](https://user-images.githubusercontent.com/27696701/137914333-04feaef3-7f87-4b76-b838-91ed48f2d1c9.png)

Work-around:

Downgrade to v3.1.4 could prevent the TypeError.

**Comment by 12wrigja** [comment]
Sorry I didn't see this till now - I think I'm running into similar issues in a different environment and was reminded of this issue.

Did you try rebuilding using a higher target in the tsconfig (maybe even just ESNext?) and seeing what webpack produces as output? I don't think the typescript target level matters a whole lot, and if we can fix the UMD bundle as a result of changing it that sounds good.

> Finally, I suppose this commit is no longer working.

Can you elaborate?

**Comment by Leslie-Wong-H** [comment]
Since the Webpack version is kind of outdated for the project I mentioned, I don't think that is the focus of this issue, after the above investigation. 

Instead, we should manage to keep the bundles of this project as consistent as they were like in 3.1.*, to prevent disaster for the downstream consumers. The main goal of TS migration should be to catch more implicit bugs within the project. 

After carefully inspecting the TS migration PR #67, I spot some contradictions. 
1. The babel() statement at rollup.config.js makes no effect on the generated UMD bundle. 
```js
  {
    input: input,
    plugins: [
      typescript(),
      babel(),
```
At the first attempt, I directly ran "npm run build", formatting the dist code, then commented "babel()", "npm run build" and formation again. Finally, use the "compare two files" functionality of VScode to compare the UMD bundles. 
Surprisingly, they are identical. See results comparing [es2015_babel/jsbi-umd.js](https://github.com/Leslie-Wong-H/jsbi/blob/verify_bundle/es2015_babel/jsbi-umd.js) and [es2015_nobabel/jsbi-umd.js](https://github.com/Leslie-Wong-H/jsbi/blob/verify_bundle/es2015_nobabel/jsbi-umd.js)

Next, I changed the target at tsconfig.json to "es5" and repeated the above steps. Once again they are identical. 
See [es5_babel](https://github.com/Leslie-Wong-H/jsbi/blob/verify_bundle/es5_babel/jsbi-umd.js) and [es5_nobabel](https://github.com/Leslie-Wong-H/jsbi/blob/verify_bundle/es5_nobabel/jsbi-umd.js)


2. The npm script "build" is antilogous.
> "build": "tsc && for f in tsc-out/*.js; do mv -- \"$f\" \"${f%.js}.mjs\"; done && rollup --config rollup.config.js",

The latter command "rollup --config rollup.config.js" makes tsc-out/jsbi.mjs utterly nonsense in the final bundles, given that the "input" variable on rollup.config.js is "lib/jsbi.ts", not "tsc-out/jsbi.mjs". So the latter command just ignores the former tsc, and then "typescript()" on rollup.config.js will do the tsc compilation process again. Duplicate compilation processes.
At this point. "typescript()" will read tsconfig.json, set the target to es2015, and then bundle, unified for cjs, umd and mjs. (babel not working concerning the above observation.) However, if we look at the bundle code of v3.1.6, [cjs](https://unpkg.com/jsbi@3.1.6/dist/jsbi-cjs.js) and [mjs](https://unpkg.com/jsbi@3.1.6/dist/jsbi.mjs) are es2015-like (containing "static"), and [umd](https://unpkg.com/jsbi@3.1.6/dist/jsbi-umd.js) is es5 compatible (no "static"). The formatted 3.1.6 bundle codes are [here](https://github.com/Leslie-Wong-H/jsbi/tree/verify_bundle/3.1.6_dist).

![image](https://user-images.githubusercontent.com/27696701/140651020-ae9ad5c4-3b16-4ccd-92cd-29ebddbd9cc7.png)

![image](https://user-images.githubusercontent.com/27696701/140651034-3a95e737-5579-42eb-be99-b20517afd179.png)

![image](https://user-images.githubusercontent.com/27696701/140651046-d18bb078-0365-4ce8-b81a-378f92564b06.png)


3. The bundle process needs to change despite [the rhetoric](https://github.com/GoogleChromeLabs/jsbi/pull/67#issuecomment-898649288) that TypeScript can not handle class inheritance in es5 well.
```
// tsconfig.json
target: "es2015"
````
The target is reasonable concerning the rhetoric, but it should not account for generating cjs, mjs and umd bundles unifiedly, ruining the previous endeavor to make JSBI browser-friendly. After all, the existence of JSBI is to provide BigInt support for older browsers. Yet now it is gone. To fix this, clearly a better and safe bundle process is to set tsc-out/jsbi.mjs as input on rollup.config.js, and remove the rollup-typescript package, which also makes "build" more accountable. In this way, the introduction of TypeScript is only to enhance dev experience (catch bug earlier at compile time), and leave the bundle grind to babel, just as before, resolving the problem of compiling class inheritance in es5 well.

The bundle output of my attempt by commenting "typescript()" and set "const input = 'tsc-out/jsbi.mjs';". [Link](https://github.com/Leslie-Wong-H/jsbi/tree/verify_bundle/custom_dist)

![image](https://user-images.githubusercontent.com/27696701/140653449-55c63b12-7ca8-446e-bfc1-e8c654debaea.png)

![image](https://user-images.githubusercontent.com/27696701/140653479-0911f7ef-3be0-480f-a491-fdde3583d750.png)

![image](https://user-images.githubusercontent.com/27696701/140653495-22c9c953-c5eb-46e5-ae3c-a007595e459a.png)

**Comment by Leslie-Wong-H** [comment]
Related discussion: 
The npm script "dev" should change to "tsc --watch", after the bundle process reform above. The "dev" is not related to the bundle. Keep bundle separated and consistent?

**Comment by 12wrigja** [comment]
I've opened a PR to fix the issues with the prototype, but this doesn't resolve the issues with the build system not actually optimizing this for IE11 (e.g ES5 output).

**Comment by 12wrigja** [comment]
@Leslie-Wong-H Your proposal above to split out using the typescript plugin and instead use the .mjs output directly sounds good to me. Would you like to send a PR to implement that? If not I can send a PR sometime this week. Thanks for digging into this.

My guess as to why Babel isn't transpiling properly is because it of the file extensions involved in the output from the typescript plugin - see https://github.com/rollup/rollup-plugin-babel/issues/255.
