### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by munizart** [GoogleChromeLabs/jsbi#9]
It says on line 62 `Modulus` where it should be read as `Remainder`, as there isn't a modulus operator in JS.
Please note that remainder and modulus may seem to be idempotent, but it's only true over natural numbers, for integers modulus differ from remainder when dividend is negative.
Ex:
```javascript
-3 % 4 === -3
modulus(-3, 4) === 1
```

I would open a PR, but i ain't willing to sign a CLA.

Thanks,

**Comment by mathiasbynens** [comment]
For future reference, this is about the following line:

```
| Modulus                     | `c = a % b`    | `c = a.remainder(b)`      |
```
