### ISSUE TITLE
Generate random JSBI numbers to use in tests

### ISSUE THREAD

**Issue by brunomacf** [GoogleChromeLabs/jsbi#94]
Is it possible to generate random JSBI numbers to be used in tests? I'm thinking about using something like [fast-check](https://github.com/dubzzz/fast-check) in tests.

**Comment by 12wrigja** [comment]
The existing generate_benchmark script does some of this: https://github.com/GoogleChromeLabs/jsbi/blob/c40371e089d1433bd8ff20b7a5be617d0561e85c/scripts/generate-benchmark.py#L162-L172

**Comment by brunomacf** [comment]
Nice!! Thanks a lot @12wrigja!
